/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Volunteer } from "./Volunteer";
import { VolunteerCountArgs } from "./VolunteerCountArgs";
import { VolunteerFindManyArgs } from "./VolunteerFindManyArgs";
import { VolunteerFindUniqueArgs } from "./VolunteerFindUniqueArgs";
import { CreateVolunteerArgs } from "./CreateVolunteerArgs";
import { UpdateVolunteerArgs } from "./UpdateVolunteerArgs";
import { DeleteVolunteerArgs } from "./DeleteVolunteerArgs";
import { VolunteerService } from "../volunteer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Volunteer)
export class VolunteerResolverBase {
  constructor(
    protected readonly service: VolunteerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "read",
    possession: "any",
  })
  async _volunteersMeta(
    @graphql.Args() args: VolunteerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Volunteer])
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "read",
    possession: "any",
  })
  async volunteers(
    @graphql.Args() args: VolunteerFindManyArgs
  ): Promise<Volunteer[]> {
    return this.service.volunteers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Volunteer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "read",
    possession: "own",
  })
  async volunteer(
    @graphql.Args() args: VolunteerFindUniqueArgs
  ): Promise<Volunteer | null> {
    const result = await this.service.volunteer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Volunteer)
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "create",
    possession: "any",
  })
  async createVolunteer(
    @graphql.Args() args: CreateVolunteerArgs
  ): Promise<Volunteer> {
    return await this.service.createVolunteer({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Volunteer)
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async updateVolunteer(
    @graphql.Args() args: UpdateVolunteerArgs
  ): Promise<Volunteer | null> {
    try {
      return await this.service.updateVolunteer({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Volunteer)
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "delete",
    possession: "any",
  })
  async deleteVolunteer(
    @graphql.Args() args: DeleteVolunteerArgs
  ): Promise<Volunteer | null> {
    try {
      return await this.service.deleteVolunteer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
