/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VolunteerService } from "../volunteer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VolunteerCreateInput } from "./VolunteerCreateInput";
import { Volunteer } from "./Volunteer";
import { VolunteerFindManyArgs } from "./VolunteerFindManyArgs";
import { VolunteerWhereUniqueInput } from "./VolunteerWhereUniqueInput";
import { VolunteerUpdateInput } from "./VolunteerUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VolunteerControllerBase {
  constructor(
    protected readonly service: VolunteerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Volunteer })
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVolunteer(
    @common.Body() data: VolunteerCreateInput
  ): Promise<Volunteer> {
    return await this.service.createVolunteer({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        phone: true,
        availability: true,
        name: true,
        email: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Volunteer] })
  @ApiNestedQuery(VolunteerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async volunteers(@common.Req() request: Request): Promise<Volunteer[]> {
    const args = plainToClass(VolunteerFindManyArgs, request.query);
    return this.service.volunteers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        phone: true,
        availability: true,
        name: true,
        email: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Volunteer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async volunteer(
    @common.Param() params: VolunteerWhereUniqueInput
  ): Promise<Volunteer | null> {
    const result = await this.service.volunteer({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        phone: true,
        availability: true,
        name: true,
        email: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Volunteer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVolunteer(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() data: VolunteerUpdateInput
  ): Promise<Volunteer | null> {
    try {
      return await this.service.updateVolunteer({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          phone: true,
          availability: true,
          name: true,
          email: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Volunteer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVolunteer(
    @common.Param() params: VolunteerWhereUniqueInput
  ): Promise<Volunteer | null> {
    try {
      return await this.service.deleteVolunteer({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          phone: true,
          availability: true,
          name: true,
          email: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
